name: Caliper test
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: autochannel
    contracts:
      - id: KBA-Automobile

organizations:
  - mspid: manufacturer-auto-com
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: "../Automobile-Network/organizations/peerOrganizations/manufacturer.auto.com/users/User1@manufacturer.auto.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../Automobile-Network/organizations/peerOrganizations/manufacturer.auto.com/users/User1@manufacturer.auto.com/msp/signcerts/cert.pem"
    peers:
      - endpoint: localhost:7051
        grpcOptions:
          ssl-target-name-override: peer0.manufacturer.auto.com
          grpc.keepalive_time_ms: 600000
        tlsCACerts:
          path: "../Automobile-Network/organizations/peerOrganizations/manufacturer.auto.com/peers/peer0.manufacturer.auto.com/tls/tlscacerts/tls-localhost-7054-ca-manufacturer.pem"
